### ISSUE TITLE
Find a better name

### ISSUE THREAD

**Issue by wernight** [JeremySkinner/Phantom#17]
The name "Phantom" is not unique at all as it means Ghost and makes finding this project harder. Also it doesn't to be much related to "Make" and ".NET" (even though I can see it's related to 'Boo').

Just a suggetion.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, but I don't currently have any plans to change the name. You're right that I chose the name because it was related to Boo.

**Comment by wernight** [comment]
No problem. Just found that a tool that seem much better than Rake should be easier to find. btw any plan for a Jenkins plugin?

**Comment by JeremySkinner** [comment]
No plans for a plugin I'm afraid...Phantom was only ever an experimental project, and I'm no longer actively working on it. That being said, if you or someone else wanted to write such a plugin and submit it ad a pull request the I'd be happy to include it.

**Comment by wernight** [comment]
I've no knowledge of such but I'll keep it in mind if I find the occasion (like having a large project using it).

**Comment by mausch** [comment]
@wernight: I don't see why you couldn't just run Phantom as a regular executable... don't know about Jenkins but TeamCity doesn't need any kind of plugins to run most custom builders... 
BTW: you might be interested in FAKE: https://github.com/forki/FAKE
